appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: DlPJN+6MMEN6aRxuZws9kfHgGJlToO01ZGpPblArP7ZcYRB2rH2YTJtSgGQoq2MXEBhS72ReM1JPHN8kp+0rkesD+ps7Got27RgYaaY2gNZEVelDvqVVChoNk0IjTmrdXAFOKhMidxkLymFNSmcgUhG8CQnoq7lmgYlJgR64hV0YmbkmETvCnNRBdAwxE9kMLkBwsCvJyYuk2Mvdvp+FwYj3qgbFCDeRMPD6hzYFl/RzCluIHYi2jPMnJkQ8HsP0rUZjZ3uW4PGYQkgNjDuJTgXLmwMQXmZcqqci3oh/z60zDAITrBRLH9gKkPiYr72teVCA+/NPrScDUpLSkIFzECqaELpvr2NZpNGjgx5F124oPNvluzER6qhPt4zwFm/93qsyN/ugebfM12Noh/4KtffC8VU+MjsG4idWxiKP2V15ZEhRcKUY1Z3/Pee42fSNm7abtYg3hoHZKDvI9xQHR+AN6sjiMbH/V9GnqN5SSTBlVdBKD2uBJJ6izTleHp7wBVj+qZ0e9icYWMTPvf+bOaMcxZN262TWujA4mp0O1YOQAwP/MJewDFZpwjd+fgEayBp2il1XqjOpwB3WeVZMUZkQLqkVw2H4U2UnB+u4vi+5VO0nGCvLJOd2bwjR5VoeE61H6JSKxJBsTqYYLg/Tbi4JOAZUY8SmWqrLbfk6Gdg=}
